package templates

import "text/template"

// RunnerData holds data for the runner template.
type RunnerData struct {
	RuntimePackage  string
	RegistryPackage string
	ConfigPackage   string
}

const runnerTemplateContent = `
// Code generated by jone. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"

	"{{ .RuntimePackage }}"
	"{{ .RegistryPackage }}"
	joneconfig "{{ .ConfigPackage }}"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: runner <migrate:latest|migrate:down|migrate:rollback> [flags]")
		os.Exit(1)
	}

	command := os.Args[1]

	// Define flags
	allFlag := flag.Bool("all", false, "Rollback all migrations")

	// Parse flags (skip command name)
	flag.CommandLine.Parse(os.Args[2:])

	cfg := &joneconfig.Config

	// Create schema and open database connection
	s := jone.NewSchema(cfg)
	if err := s.Open(); err != nil {
		fmt.Printf("Failed to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer s.Close()

	params := jone.RunParams{
		Config:        cfg,
		Registrations: registry.Registrations,
		Schema:        s,
		Options: jone.RunOptions{
			All:  *allFlag,
			Args: flag.Args(),
		},
	}

	switch command {
	case "migrate:latest":
		if err := jone.RunLatest(params); err != nil {
			fmt.Printf("Migration failed: %v\n", err)
			os.Exit(1)
		}
	case "migrate:down":
		if err := jone.RunDown(params); err != nil {
			fmt.Printf("Rollback failed: %v\n", err)
			os.Exit(1)
		}
	case "migrate:rollback":
		if err := jone.RunRollback(params); err != nil {
			fmt.Printf("Rollback failed: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Printf("Unknown command: %s\n", command)
		os.Exit(1)
	}
}
`

// Runner is the parsed template for generating the migration runner.
var Runner = template.Must(template.New("runner").Parse(runnerTemplateContent))

// RenderRunner generates the _runner.go content.
func RenderRunner(data RunnerData) ([]byte, error) {
	return Render(Runner, data)
}
