package templates

import "text/template"

// RunnerData holds data for the runner template.
type RunnerData struct {
	RuntimePackage  string
	RegistryPackage string
	ConfigPackage   string
}

const runnerTemplateContent = `
// Code generated by jone. DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	"{{ .RuntimePackage }}"
	"{{ .RegistryPackage }}"
	joneconfig "{{ .ConfigPackage }}"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: _runner <migrate:up|migrate:down>")
		os.Exit(1)
	}

	cfg := &joneconfig.Config

	switch os.Args[1] {
	case "migrate:up":
		if err := jone.RunUp(cfg, registry.Registrations); err != nil {
			fmt.Printf("Migration failed: %v\n", err)
			os.Exit(1)
		}
	case "migrate:down":
		if err := jone.RunDown(cfg, registry.Registrations); err != nil {
			fmt.Printf("Rollback failed: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Printf("Unknown command: %s\n", os.Args[1])
		os.Exit(1)
	}
}
`

// Runner is the parsed template for generating the migration runner.
var Runner = template.Must(template.New("runner").Parse(runnerTemplateContent))

// RenderRunner generates the _runner.go content.
func RenderRunner(data RunnerData) ([]byte, error) {
	return Render(Runner, data)
}
