package cli

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/Grandbusta/jone/cmd/jone/templates"
	"github.com/Grandbusta/jone/internal/term"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initializes a jone project",
	Long:  `Initializes a jone project with the required folder structure and configuration`,
	Run:   initJone,
}

func init() {
	initCmd.Flags().StringP("db", "d", "postgres", "Database type (postgres, mysql, sqlite)")
}

func initJone(cmd *cobra.Command, args []string) {
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to get working directory: %v\n", err)
		os.Exit(1)
	}

	dbFlag, _ := cmd.Flags().GetString("db")
	// Normalize database name
	var database string
	switch dbFlag {
	case "postgres", "postgresql", "pg":
		database = "postgres"
	case "mysql", "mariadb":
		database = "mysql"
	case "sqlite", "sqlite3":
		database = "sqlite"
	default:
		fmt.Printf("Unsupported database: %s\n", dbFlag)
		fmt.Println("Supported databases: postgres, mysql, sqlite")
		os.Exit(1)
	}

	modFilePath := FindOrCreateGoMod(cwd)
	if modFilePath == "" {
		fmt.Println("Failed to find or create go.mod file.")
		os.Exit(1)
	}

	if !JoneDependencyPresent(modFilePath) {
		fmt.Println("jone is not installed in this project. Installing...")
		goGetCmd := exec.Command("go", "get", RuntimePackage)
		goGetCmd.Dir = cwd
		goGetCmd.Stdout = os.Stdout
		goGetCmd.Stderr = os.Stderr
		if err := goGetCmd.Run(); err != nil {
			fmt.Printf("Failed to install jone: %v\n", err)
			os.Exit(1)
		}
		fmt.Println(term.GreenText("jone installed successfully."))
	}

	if err := createJoneFolderAndFiles(cwd, database); err != nil {
		fmt.Printf("Error creating jone files: %v\n", err)
		os.Exit(1)
	}

	// Install database driver
	driverPackage := getDriverPackage(database)
	if driverPackage != "" {
		fmt.Printf("%s\n", term.YellowText(fmt.Sprintf("Installing database driver (%s)...", driverPackage)))
		goGetCmd := exec.Command("go", "get", driverPackage)
		goGetCmd.Dir = cwd
		goGetCmd.Stdout = os.Stdout
		goGetCmd.Stderr = os.Stderr
		if err := goGetCmd.Run(); err != nil {
			fmt.Printf("Warning: Failed to install driver: %v\n", err)
			fmt.Printf("You may need to run: go get %s\n", driverPackage)
		}
	}

	fmt.Println(term.GreenText(fmt.Sprintf("jone init complete (database: %s).", database)))
}

func getDriverPackage(database string) string {
	switch database {
	case "postgres":
		return "github.com/jackc/pgx/v5/stdlib"
	case "mysql":
		return "github.com/go-sql-driver/mysql"
	case "sqlite":
		return "github.com/mattn/go-sqlite3"
	default:
		return ""
	}
}

func createJoneFolderAndFiles(cwd string, database string) error {
	joneFolderPath := filepath.Join(cwd, JoneFolderPath)

	// Create jone folder
	if _, err := os.Stat(joneFolderPath); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			if err := os.Mkdir(joneFolderPath, 0755); err != nil {
				return fmt.Errorf("creating jone folder: %w", err)
			}
		} else {
			return fmt.Errorf("checking jone folder: %w", err)
		}
	}

	// Create jonefile.go
	joneFilePath := filepath.Join(cwd, JoneFilePath)
	if _, err := os.Stat(joneFilePath); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			if err := writeJoneFile(joneFilePath, database); err != nil {
				return err
			}
		} else {
			return fmt.Errorf("checking jonefile.go: %w", err)
		}
	}

	// Create migrations folder
	migrationsPath := filepath.Join(cwd, MigrationsPath)
	if err := os.MkdirAll(migrationsPath, 0755); err != nil {
		return fmt.Errorf("creating migrations folder: %w", err)
	}

	// Create registry folder with empty registry.go
	registryPath := filepath.Join(migrationsPath, "registry")
	if err := os.MkdirAll(registryPath, 0755); err != nil {
		return fmt.Errorf("creating registry folder: %w", err)
	}

	// Create initial empty registry.go
	registryFile := filepath.Join(registryPath, "registry.go")
	if _, err := os.Stat(registryFile); errors.Is(err, os.ErrNotExist) {
		if err := writeEmptyRegistry(registryFile); err != nil {
			return err
		}
	}

	// Create or update .gitignore at project root
	if err := ensureGitignore(cwd); err != nil {
		return err
	}

	return nil
}

func writeJoneFile(path string, database string) error {
	content, err := templates.RenderJoneFile(templates.JoneFileData{
		RuntimePackage: RuntimePackage,
		Database:       database,
	})
	if err != nil {
		return fmt.Errorf("rendering jonefile template: %w", err)
	}

	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("writing jonefile.go: %w", err)
	}

	return nil
}

func writeEmptyRegistry(path string) error {
	content := fmt.Sprintf(`// Code generated by jone. DO NOT EDIT.
package registry

import %q

var Registrations = []jone.Registration{}
`, RuntimePackage)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing registry.go: %w", err)
	}

	return nil
}

func ensureGitignore(projectRoot string) error {
	gitignorePath := filepath.Join(projectRoot, ".gitignore")
	runnerEntry := "jone/.runner/"

	// Check if .gitignore exists
	content, err := os.ReadFile(gitignorePath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			// Create new .gitignore with .runner entry
			return os.WriteFile(gitignorePath, []byte(runnerEntry+"\n"), 0o644)
		}
		return fmt.Errorf("reading .gitignore: %w", err)
	}

	// Check if .runner is already in .gitignore
	lines := string(content)
	if contains(lines, runnerEntry) {
		return nil // Already present
	}

	// Append .runner entry
	newContent := lines
	if len(lines) > 0 && lines[len(lines)-1] != '\n' {
		newContent += "\n"
	}
	newContent += runnerEntry + "\n"

	return os.WriteFile(gitignorePath, []byte(newContent), 0o644)
}

func contains(s, substr string) bool {
	for _, line := range filepath.SplitList(s) {
		if line == substr {
			return true
		}
	}
	// Simple check for substring
	return len(s) >= len(substr) && (s == substr ||
		len(s) > len(substr) && (s[:len(substr)+1] == substr+"\n" ||
			s[len(s)-len(substr)-1:] == "\n"+substr ||
			len(s) > len(substr)+1 && contains(s, "\n"+substr+"\n")))
}
